#!/usr/bin/with-contenv bash

pip3 install -U pip
# Make sure to install setuptools version >=36 to avoid a race condition, see:
# https://github.com/pypa/setuptools/issues/951
pip3 install -U setuptools>=36
pip3 install -U urllib3[socks]
pip3 install -U chardet
pip3 install -U irc_bot
pip3 install -U rarfile
pip3 install -U subliminal


# Install libtorrent-rasterbar, a dependency for e.g.
# flexget plugin `convert_magnet`.
apk add --update --no-cache --virtual=build-dependencies \
    apk-tools

# Dependency for libtorrent-rasterbar.
apk add --no-cache \
    boost-python@edge \
    boost-system@edge \
    libressl-dev@edge

# libtorrent-rasterbar contains the python bindings libtorrent.
apk add --no-cache \
    libcrypto1.1@edge \
    libssl1.1@edge \
    libtorrent-rasterbar@testing

# Install flexget last (it might force specific versions of other packages).
pip3 install -U flexget
